version: "3.8"
services:
  app1:
    container_name: app1
    build:
      context: ./app1
    networks:
      nginxnet:
        aliases:
          - app1

  app2:
    container_name: app2
    build:
      context: ./app2
    networks:
      nginxnet:
        aliases:
          - app2

  front:
    image: nginx:latest
    container_name: front
    volumes:
      - ./front/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
    networks:
      nginxnet:
        aliases:
          - front

networks:
  nginxnet:
